build:
  build_starting:
      image: python:2
      commands:
          - echo "Beginning new build"
  run_tests:
      image: python:2-onbuild
      environment:
            - ANSIBLE_NET_USERNAME=$$ANSIBLE_NET_USERNAME
            - ANSIBLE_NET_PASSWORD=$$ANSIBLE_NET_PASSWORD
      commands:
          - pip install -r requirements.txt
          - echo $ANSIBLE_NET_USERNAME
          - ansible-playbook -i test main.yml
