build:
  build_starting:
      image: python:2
      commands:
          - echo "*******************************"
          - echo "*                             *"
          - echo "* Beginning new build         *"
          - echo "*                             *"
          - echo "*******************************"
  deploy_to_test:
      image: hpreston/drone-ansible-netdevops
      environment:
            - ANSIBLE_NET_USERNAME=$$ANSIBLE_NET_USERNAME
            - ANSIBLE_NET_PASSWORD=$$ANSIBLE_NET_PASSWORD
      commands:
          - echo "*******************************"
          - echo "*                             *"
          - echo "* Deploying Config to test    *"
          - echo "*                             *"
          - echo "*******************************"
          - echo "Network Username> $ANSIBLE_NET_USERNAME"
          - ansible-playbook -i test.yml main.yml
  test_new_strings:
      image: hpreston/drone-ansible-netdevops
      environment:
            - ANSIBLE_NET_USERNAME=$$ANSIBLE_NET_USERNAME
            - ANSIBLE_NET_PASSWORD=$$ANSIBLE_NET_PASSWORD
      commands:
          - echo "*******************************"
          - echo "*                             *"
          - echo "* Running Network Tests       *"
          - echo "*                             *"
          - echo "*******************************"
          - echo "Network Username> $ANSIBLE_NET_USERNAME"
          - ansible-playbook -i test.yml testing-playbook.yml
