build:
  build_starting:
      image: python:2
      commands:
          - echo "Beginning new build"
  deploy_to_test:
      image: python:2-onbuild
      environment:
            - ANSIBLE_NET_USERNAME=$$ANSIBLE_NET_USERNAME
            - ANSIBLE_NET_PASSWORD=$$ANSIBLE_NET_PASSWORD
      commands:
          - pip install -r requirements.txt
          - echo $ANSIBLE_NET_USERNAME
          - ansible-playbook -i test.yml main.yml
  test_new_strings:
      image: python:2-onbuild
      environment:
            - ANSIBLE_NET_USERNAME=$$ANSIBLE_NET_USERNAME
            - ANSIBLE_NET_PASSWORD=$$ANSIBLE_NET_PASSWORD
      commands:
          - pip install -r requirements.txt
          - echo $ANSIBLE_NET_USERNAME
          - ansible-playbook -i test.yml testing-playbook.yml
