build:
  build_starting:
      image: python:2
      commands:
          - echo "** Beginning new build"
  deploy_to_test:
      image: hpreston/drone-ansible-netdevops
      environment:
            - ANSIBLE_NET_USERNAME=$$ANSIBLE_NET_USERNAME
            - ANSIBLE_NET_PASSWORD=$$ANSIBLE_NET_PASSWORD
      commands:
          - echo "** Deploying Config to test"
          - echo "Network Username> $ANSIBLE_NET_USERNAME"
          - ansible-playbook -i test.yml main.yml
  test_new_strings:
      image: hpreston/drone-ansible-netdevops
      environment:
            - ANSIBLE_NET_USERNAME=$$ANSIBLE_NET_USERNAME
            - ANSIBLE_NET_PASSWORD=$$ANSIBLE_NET_PASSWORD
      commands:
          - echo "** Running Network Tests"
          - echo "Network Username> $ANSIBLE_NET_USERNAME"
          - ansible-playbook -v -i test.yml testing-playbook.yml
