- hosts: all
  connection: local
  gather_facts: yes
  vars_files:
    - snmp.yml
  tasks:
    - snmp_facts:
        host: '{{ inventory_hostname }}'
        version: v2c
        community: "{{ snmp_read_only }}"

    - debug:
        msg: "SNMP System Name: {{ ansible_facts.ansible_sysname }} SNMP OID: {{ ansible_facts.ansible_sysobjectid }}"
