
- name: Get current SNMP configuration
  ios_command:
    provider: "{{ cli }}"
    port: "{{ port }}"
    commands: "show running | inc snmp-server community"
  register: snmp_before

- name: Remove existing SNMP configuration
  when:  item != ''
  ios_config:
    provider: "{{ cli }}"
    port: "{{ port }}"

    lines: "no {{ item }}"
  with_items: "{{ snmp_before.stdout_lines[0] }}"

- name: Configure SNMP
  ios_config:
    provider: "{{ cli }}"
    port: "{{ port }}"
    lines:
      - snmp-server community {{ snmp_read_only }}
      - snmp-server community {{ snmp_read_write }}
      - snmp-server enable traps snmp linkdown linkup
      - snmp-server host 172.29.52.12 version 2c public
    before: default snmp-server
    match: exact
    replace: block
